/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testingprocedurecombinations.classicmodelsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

import com.testingprocedurecombinations.classicmodelsdb.models.procedure.*;

@Service
public class ClassicModelsDBProcedureExecutorServiceImpl implements ClassicModelsDBProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ClassicModelsDBProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("ClassicModelsDBWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;

    @Transactional(value = "ClassicModelsDBTransactionManager")
    @Override
    public ProcedureOutOutInResponse executeProcedure_OUT_OUT_IN(String offCode) {
        Map params = new HashMap(3);

        params.put("offCode", offCode);

        return procedureExecutor.executeNamedProcedure("Procedure_OUT_OUT_IN", params, ProcedureOutOutInResponse.class);
    }

    @Transactional(value = "ClassicModelsDBTransactionManager")
    @Override
    public ProcedureOutOutInoutResponse executeProcedure_OUT_OUT_INOUT(Integer empNumber) {
        Map params = new HashMap(3);

        params.put("empNumber", empNumber);

        return procedureExecutor.executeNamedProcedure("Procedure_OUT_OUT_INOUT", params, ProcedureOutOutInoutResponse.class);
    }

}


