/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testingprocedurecombinations.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.sql.Date;
import java.util.List;

import com.testingprocedurecombinations.classicmodels.models.procedure.*;

@Deprecated
public interface ClassicmodelsProcedureExecutorService_V1 {

    @Deprecated
    List<Object> executeProcedure_INOUT_OUT_OUT(Date ordrDate);

    @Deprecated
    List<Object> executeProcedure_INOUT_IN_IN(Integer result1, Integer numerator, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_INOUT_IN_INOUT(Double result1, Integer numerator, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_INOUT_IN_OUT(Integer numerator, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_IN_OUT(Integer customerNumber);

    @Deprecated
    List<Object> executeProcedure_IN_INOUT_IN(Integer numerator, Integer res, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_OUT_IN_IN(Integer custNumber, String checkNum);

    @Deprecated
    List<Object> executeProcedure_INOUT_INOUT_IN(Integer count1, Integer count2, Integer count3, Integer inc);

    @Deprecated
    List<Object> executeProcedure_IN_INOUT_INOUT(Date reqDate, Integer ordNumber, Date shipDate);

    @Deprecated
    List<Object> executeProcedure_WithoutAnyParams();

    @Deprecated
    List<Object> executeProcedure_INOUT_INOUT_INOUT(Integer numerator, Integer denominator, Double result1);

    @Deprecated
    List<Object> executeProcedure_OUT_IN_INOUT(Date reqDate, Integer ordNumber);

    @Deprecated
    List<Object> executeProcedure_IN_INOUT(Integer custnum, String customerLevel);

    @Deprecated
    List<Object> executeProcedure_IN_IN(String empFname, Integer empNumber);

    @Deprecated
    List<Object> executeProcedure_INOUT_INOUT(Integer custnum, String customerLevel);

    @Deprecated
    List<Object> executeProcedure_INOUT_INOUT_OUT(Integer numerator, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_IN_IsList(String custNumber);

    @Deprecated
    List<Object> executeProcedure_OUT_IN_OUT(String prodLine);

    @Deprecated
    List<Object> executeProcedure_IN_OUT_OUT(Integer cutomerNumber);

    @Deprecated
    List<Object> executeProcedure_Sysparam();

    @Deprecated
    List<Object> executeProcedure_IN_OUT_INOUT(Integer numerator, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_OUT_INOUT_OUT(String prodCode);

    @Deprecated
    List<Object> executeProcedure_OUT_IN(Integer empNumber);

    @Deprecated
    List<Object> executeProcedure_OUT_INOUT_IN(Date reqDate, Integer ordNumber);

    @Deprecated
    List<Object> executeProcedure_OUT_OUT();

    @Deprecated
    List<Object> executeProcedure_INOUT_OUT_IN(Integer numerator, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_IN_IN_OUT(Date requiredDate, Integer orderNumber);

    @Deprecated
    List<Object> executeProcedure_OUT_INOUT(String prodLine);

    @Deprecated
    List<Object> executeProcedure_INOUT_OUT_INOUT(Integer numerator, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_OUT_INOUT_INOUT(Date reqDate, Integer ordNumber);

    @Deprecated
    List<Object> executeProcedure_INOUT_IN(Date giveRequiredDateGetShippedDate, Integer orderNumber);

    @Deprecated
    List<Object> executeProcedure_OUT_OUT_OUT();

    @Deprecated
    List<Object> executeProcedure_IN_INOUT_OUT(Date reqDate, Integer ordNumber);

    @Deprecated
    List<Object> executeProcedure_OUT_OUT_INOUT(Integer empNumber);

    @Deprecated
    List<Object> executeProcedure_IN_IN_INOUT(Date reqDate, Integer ordNumber, Date shipDate);

    @Deprecated
    List<Object> executeProcedure_OUT();

    @Deprecated
    List<Object> executeProcedure_IN_STRING(String countryname);

    @Deprecated
    List<Object> executeProcedure_INOUT(Integer empNumber);

    @Deprecated
    List<Object> executeProcedure_INOUT_OUT(Integer custnum);

    @Deprecated
    List<Object> executeProcedure_OUT_OUT_IN(Integer offCode);

    @Deprecated
    List<Object> executePROCEDURE_IN_OUT_IN(Integer numerator, Integer denominator);

    @Deprecated
    List<Object> executeProcedure_IN(Integer empNumber);

    @Deprecated
    List<Object> executeProcedure_IN_IN_IN(Integer artId, Integer tagId, String blnak);

    @Deprecated
    List<Object> executeProcedure_getProductDetails(String prodLine);

}


