/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureOutInResponse implements Serializable {


    @JsonProperty("empFName")
    @ColumnAlias("empFName")
    private String empFname;

    public String getEmpFname() {
        return this.empFname;
    }

    public void setEmpFname(String empFname) {
        this.empFname = empFname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureOutInResponse)) return false;
        final ProcedureOutInResponse procedureOutInResponse = (ProcedureOutInResponse) o;
        return Objects.equals(getEmpFname(), procedureOutInResponse.getEmpFname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpFname());
    }
}
