/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureOutInInoutResponse implements Serializable {


    @JsonProperty("shipDate")
    @ColumnAlias("shipDate")
    private Date shipDate;

    @JsonProperty("ordNumber")
    @ColumnAlias("ordNumber")
    private Integer ordNumber;

    public Date getShipDate() {
        return this.shipDate;
    }

    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }

    public Integer getOrdNumber() {
        return this.ordNumber;
    }

    public void setOrdNumber(Integer ordNumber) {
        this.ordNumber = ordNumber;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureOutInInoutResponse)) return false;
        final ProcedureOutInInoutResponse procedureOutInInoutResponse = (ProcedureOutInInoutResponse) o;
        return Objects.equals(getShipDate(), procedureOutInInoutResponse.getShipDate()) &&
                Objects.equals(getOrdNumber(), procedureOutInInoutResponse.getOrdNumber());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getShipDate(),
                getOrdNumber());
    }
}
