/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureInoutInoutInoutResponse implements Serializable {


    @JsonProperty("numerator")
    @ColumnAlias("numerator")
    private Integer numerator;

    @JsonProperty("denominator")
    @ColumnAlias("denominator")
    private Integer denominator;

    @JsonProperty("result1")
    @ColumnAlias("result1")
    private Double result1;

    public Integer getNumerator() {
        return this.numerator;
    }

    public void setNumerator(Integer numerator) {
        this.numerator = numerator;
    }

    public Integer getDenominator() {
        return this.denominator;
    }

    public void setDenominator(Integer denominator) {
        this.denominator = denominator;
    }

    public Double getResult1() {
        return this.result1;
    }

    public void setResult1(Double result1) {
        this.result1 = result1;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureInoutInoutInoutResponse)) return false;
        final ProcedureInoutInoutInoutResponse procedureInoutInoutInoutResponse = (ProcedureInoutInoutInoutResponse) o;
        return Objects.equals(getNumerator(), procedureInoutInoutInoutResponse.getNumerator()) &&
                Objects.equals(getDenominator(), procedureInoutInoutInoutResponse.getDenominator()) &&
                Objects.equals(getResult1(), procedureInoutInoutInoutResponse.getResult1());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNumerator(),
                getDenominator(),
                getResult1());
    }
}
