/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureInoutInResponse implements Serializable {


    @JsonProperty("GiveRequiredDateGetShippedDate")
    @ColumnAlias("GiveRequiredDateGetShippedDate")
    private Date giveRequiredDateGetShippedDate;

    public Date getGiveRequiredDateGetShippedDate() {
        return this.giveRequiredDateGetShippedDate;
    }

    public void setGiveRequiredDateGetShippedDate(Date giveRequiredDateGetShippedDate) {
        this.giveRequiredDateGetShippedDate = giveRequiredDateGetShippedDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureInoutInResponse)) return false;
        final ProcedureInoutInResponse procedureInoutInResponse = (ProcedureInoutInResponse) o;
        return Objects.equals(getGiveRequiredDateGetShippedDate(), procedureInoutInResponse.getGiveRequiredDateGetShippedDate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getGiveRequiredDateGetShippedDate());
    }
}
