/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureOutInoutOutResponse implements Serializable {


    @JsonProperty("prodName")
    @ColumnAlias("prodName")
    private String prodName;

    @JsonProperty("prodCode")
    @ColumnAlias("prodCode")
    private String prodCode;

    @JsonProperty("prodDesc")
    @ColumnAlias("prodDesc")
    private String prodDesc;

    public String getProdName() {
        return this.prodName;
    }

    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    public String getProdCode() {
        return this.prodCode;
    }

    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    public String getProdDesc() {
        return this.prodDesc;
    }

    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureOutInoutOutResponse)) return false;
        final ProcedureOutInoutOutResponse procedureOutInoutOutResponse = (ProcedureOutInoutOutResponse) o;
        return Objects.equals(getProdName(), procedureOutInoutOutResponse.getProdName()) &&
                Objects.equals(getProdCode(), procedureOutInoutOutResponse.getProdCode()) &&
                Objects.equals(getProdDesc(), procedureOutInoutOutResponse.getProdDesc());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getProdName(),
                getProdCode(),
                getProdDesc());
    }
}
