/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureOutOutInResponse implements Serializable {


    @JsonProperty("addrLine1")
    @ColumnAlias("addrLine1")
    private String addrLine1;

    @JsonProperty("addrLine2")
    @ColumnAlias("addrLine2")
    private String addrLine2;

    public String getAddrLine1() {
        return this.addrLine1;
    }

    public void setAddrLine1(String addrLine1) {
        this.addrLine1 = addrLine1;
    }

    public String getAddrLine2() {
        return this.addrLine2;
    }

    public void setAddrLine2(String addrLine2) {
        this.addrLine2 = addrLine2;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureOutOutInResponse)) return false;
        final ProcedureOutOutInResponse procedureOutOutInResponse = (ProcedureOutOutInResponse) o;
        return Objects.equals(getAddrLine1(), procedureOutOutInResponse.getAddrLine1()) &&
                Objects.equals(getAddrLine2(), procedureOutOutInResponse.getAddrLine2());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAddrLine1(),
                getAddrLine2());
    }
}
