/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureInoutOutOutResponse implements Serializable {


    @JsonProperty("ordrDate")
    @ColumnAlias("ordrDate")
    private Date ordrDate;

    @JsonProperty("reqDate")
    @ColumnAlias("reqDate")
    private Date reqDate;

    @JsonProperty("ordrstatus")
    @ColumnAlias("ordrstatus")
    private String ordrstatus;

    public Date getOrdrDate() {
        return this.ordrDate;
    }

    public void setOrdrDate(Date ordrDate) {
        this.ordrDate = ordrDate;
    }

    public Date getReqDate() {
        return this.reqDate;
    }

    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    public String getOrdrstatus() {
        return this.ordrstatus;
    }

    public void setOrdrstatus(String ordrstatus) {
        this.ordrstatus = ordrstatus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureInoutOutOutResponse)) return false;
        final ProcedureInoutOutOutResponse procedureInoutOutOutResponse = (ProcedureInoutOutOutResponse) o;
        return Objects.equals(getOrdrDate(), procedureInoutOutOutResponse.getOrdrDate()) &&
                Objects.equals(getReqDate(), procedureInoutOutOutResponse.getReqDate()) &&
                Objects.equals(getOrdrstatus(), procedureInoutOutOutResponse.getOrdrstatus());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdrDate(),
                getReqDate(),
                getOrdrstatus());
    }
}
