/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureInStringResponseContent implements Serializable {


    @JsonProperty("officeCode")
    @ColumnAlias("officeCode")
    private String officeCode;

    @JsonProperty("city")
    @ColumnAlias("city")
    private String city;

    @JsonProperty("phone")
    @ColumnAlias("phone")
    private String phone;

    @JsonProperty("addressLine1")
    @ColumnAlias("addressLine1")
    private String addressLine1;

    @JsonProperty("addressLine2")
    @ColumnAlias("addressLine2")
    private String addressLine2;

    @JsonProperty("state")
    @ColumnAlias("state")
    private String state;

    @JsonProperty("country")
    @ColumnAlias("country")
    private String country;

    @JsonProperty("postalCode")
    @ColumnAlias("postalCode")
    private String postalCode;

    @JsonProperty("territory")
    @ColumnAlias("territory")
    private String territory;

    public String getOfficeCode() {
        return this.officeCode;
    }

    public void setOfficeCode(String officeCode) {
        this.officeCode = officeCode;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getTerritory() {
        return this.territory;
    }

    public void setTerritory(String territory) {
        this.territory = territory;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureInStringResponseContent)) return false;
        final ProcedureInStringResponseContent procedureInStringResponseContent = (ProcedureInStringResponseContent) o;
        return Objects.equals(getOfficeCode(), procedureInStringResponseContent.getOfficeCode()) &&
                Objects.equals(getCity(), procedureInStringResponseContent.getCity()) &&
                Objects.equals(getPhone(), procedureInStringResponseContent.getPhone()) &&
                Objects.equals(getAddressLine1(), procedureInStringResponseContent.getAddressLine1()) &&
                Objects.equals(getAddressLine2(), procedureInStringResponseContent.getAddressLine2()) &&
                Objects.equals(getState(), procedureInStringResponseContent.getState()) &&
                Objects.equals(getCountry(), procedureInStringResponseContent.getCountry()) &&
                Objects.equals(getPostalCode(), procedureInStringResponseContent.getPostalCode()) &&
                Objects.equals(getTerritory(), procedureInStringResponseContent.getTerritory());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOfficeCode(),
                getCity(),
                getPhone(),
                getAddressLine1(),
                getAddressLine2(),
                getState(),
                getCountry(),
                getPostalCode(),
                getTerritory());
    }
}
