/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testingprocedurecombinations.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureGetProductDetailsResponseContent implements Serializable {


    @JsonProperty("ProductDesc")
    @ColumnAlias("ProductDesc")
    private String productDesc;

    @JsonProperty("quantityInStock")
    @ColumnAlias("quantityInStock")
    private Integer quantityInStock;

    @JsonProperty("buyPrice")
    @ColumnAlias("buyPrice")
    private Double buyPrice;

    public String getProductDesc() {
        return this.productDesc;
    }

    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    public Integer getQuantityInStock() {
        return this.quantityInStock;
    }

    public void setQuantityInStock(Integer quantityInStock) {
        this.quantityInStock = quantityInStock;
    }

    public Double getBuyPrice() {
        return this.buyPrice;
    }

    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureGetProductDetailsResponseContent)) return false;
        final ProcedureGetProductDetailsResponseContent procedureGetProductDetailsResponseContent = (ProcedureGetProductDetailsResponseContent) o;
        return Objects.equals(getProductDesc(), procedureGetProductDetailsResponseContent.getProductDesc()) &&
                Objects.equals(getQuantityInStock(), procedureGetProductDetailsResponseContent.getQuantityInStock()) &&
                Objects.equals(getBuyPrice(), procedureGetProductDetailsResponseContent.getBuyPrice());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getProductDesc(),
                getQuantityInStock(),
                getBuyPrice());
    }
}
